server:
  port: 18080
spring:
  application:
    name: bookJPA-cty #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: xxx
    username: xxx
    password: xxx
  jpa: 
    database: MySQL
    show-sql: true
